Remove automatic tmuxing because of kitty

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -4,16 +4,14 @@
 
 # If this is not an interactive shell, do nothing.
 case $- in
-  *i*)
-    ;;
-  *)
-    return
-    ;;
+*i*) ;;
+*)
+	return
+	;;
 esac
 
 # First, if there's a global bashrc, load it.
 [ -f /etc/bashrc ] && . /etc/bashrc
-
 
 # Some hosts have a FQDN as their $HOSTNAME. This sucks in prompts etc.
 # Let's make sure that we have a version with _just_ the first part.
@@ -30,7 +28,7 @@ export PATH="$HOME/.local/bin::$MASTERPATH:"
 
 # If we're in Windows Terminal, advertise true-color support.
 if [ -n "$WT_SESSION" ]; then
-  export COLORTERM='truecolor'
+	export COLORTERM='truecolor'
 fi
 
 # Some tools parse this variable to find out whether the terminal's background
@@ -39,21 +37,21 @@ fi
 # background as the default, if the terminal doesn't specify anything else.
 [ -z "$COLORFGBG" ] && export COLORFGBG='7;0'
 
-# If we are in a terminal, tmux is available and we're not running from _inside_ tmux already, replace this shell with tmux.
-# Except when ~/.notmux exists.
-if [ ! -e "$HOME/.notmux" ] && [ -z "$TMUX" ] && [ -t 0 ] && command -v tmux &>/dev/null; then
-  # In tmux, all clients connected to a session share the same view on it. If you want to have different views in each
-  # client (for example every client being a new terminal emulator window in a GUI setup), you need to use tmux's
-  # "session groups" feature. However, in that setup (where a new session will be created for each terminal
-  # emulator window), closing or detaching these windows will leave behind leftover sessions in the group. Therefore
-  # I'll create the "base session" manually and then attach additional sessions and clients to it for each terminal.
-  # Session names are unique, if the base session already exists this will fail silently. Note that this failure could
-  # also mean that the session could not be created at all for some reason. I don't know why this should happen, so
-  # I'll consider it out of scope for now.
-  tmux new-session -d -t main -s main-base 2>/dev/null || true
-  # Now, actually attach to that session group using an auto-incrementing session name (by not specifying -s).
-  exec tmux new-session -t main
-fi
+# # If we are in a terminal, tmux is available and we're not running from _inside_ tmux already, replace this shell with tmux.
+# # Except when ~/.notmux exists.
+# if [ ! -e "$HOME/.notmux" ] && [ -z "$TMUX" ] && [ -t 0 ] && command -v tmux &>/dev/null; then
+#   # In tmux, all clients connected to a session share the same view on it. If you want to have different views in each
+#   # client (for example every client being a new terminal emulator window in a GUI setup), you need to use tmux's
+#   # "session groups" feature. However, in that setup (where a new session will be created for each terminal
+#   # emulator window), closing or detaching these windows will leave behind leftover sessions in the group. Therefore
+#   # I'll create the "base session" manually and then attach additional sessions and clients to it for each terminal.
+#   # Session names are unique, if the base session already exists this will fail silently. Note that this failure could
+#   # also mean that the session could not be created at all for some reason. I don't know why this should happen, so
+#   # I'll consider it out of scope for now.
+#   tmux new-session -d -t main -s main-base 2>/dev/null || true
+#   # Now, actually attach to that session group using an auto-incrementing session name (by not specifying -s).
+#   exec tmux new-session -t main
+# fi
 
 # Default umask is 0022, i.e. write permissions only for the user, not the group.
 # Some OSes have different defaults; this defines a standard for all of my machines.
